import React, { useEffect, useState } from 'react';
import { useRouter } from 'next/router';
import PageLayout from '../../src/components/PageLayout';
import { useRequireAuth } from '../../src/lib/auth';
import { useCurrentStationId } from '../../src/lib/station';
import supabase from '../../src/lib/supabaseClient';

const money = (value: unknown) => `${Number(value || 0).toLocaleString('ar-EG', { minimumFractionDigits: 2 })} ج.م`;
const info = (label: string, value?: string | null) => value ? <div><dt>{label}</dt><dd>{value}</dd></div> : null;
type InvoiceItem = { item_code?: string; item_name?: string; item_category_code?: string; item_description?: string; item_unit?: string; item_quantity?: number; item_unit_price?: number; item_discount?: number; subtotal?: number; net_amount?: number };

export default function ExtraSaleDetails() {
  const { user } = useRequireAuth(); const router = useRouter(); const stationId = useCurrentStationId(user?.id ?? null); const id = typeof router.query.id === 'string' ? router.query.id : '';
  const [sale, setSale] = useState<any>(null); const [error, setError] = useState('');
  useEffect(() => { if (!stationId || !id) return; (async () => { const { data } = await supabase.auth.getSession(); const response = await fetch(`/api/extra-sales/${id}?stationId=${encodeURIComponent(stationId)}`, { headers: data.session?.access_token ? { Authorization: `Bearer ${data.session.access_token}` } : {} }); const body = await response.json(); if (!response.ok) setError(body.error || 'تعذر تحميل الفاتورة.'); else setSale(body.sale); })(); }, [stationId, id]);
  if (error) return <PageLayout title="تفاصيل الفاتورة"><div className="empty-state"><h3>تعذر فتح الفاتورة</h3><p>{error}</p></div></PageLayout>;
  if (!sale) return <PageLayout title="تفاصيل الفاتورة"><div className="empty-state"><p>جارٍ تحميل الفاتورة…</p></div></PageLayout>;
  const items: InvoiceItem[] = Array.isArray(sale.items) && sale.items.length ? sale.items : [{ item_code: sale.item_code, item_name: sale.item_name || sale.sale_description, item_category_code: sale.item_category_code, item_description: sale.item_description || sale.sale_description, item_unit: sale.item_unit, item_quantity: sale.item_quantity, item_unit_price: sale.item_unit_price, item_discount: sale.item_discount, subtotal: sale.subtotal ?? sale.amount, net_amount: sale.net_amount ?? sale.amount }];
  const subtotal = items.reduce((sum, entry) => sum + Number(entry.subtotal || 0), 0); const discount = items.reduce((sum, entry) => sum + Number(entry.item_discount || 0), 0); const net = items.reduce((sum, entry) => sum + Number(entry.net_amount ?? Number(entry.subtotal || 0) - Number(entry.item_discount || 0)), 0);
  return <PageLayout title="الفاتورة الإلكترونية"><main className="extra-sales-page"><div className="no-print page-heading"><div><span className="eyebrow">مبيعات إضافية</span><h2>الفاتورة الإلكترونية</h2><p>{sale.invoice_number}</p></div><div className="page-header-actions"><button className="ui-button" onClick={() => window.print()}>طباعة الفاتورة</button><button className="ui-button secondary" onClick={() => router.push('/extra-sales')}>العودة</button></div></div><article className="extra-invoice"><header><b>فاتورة بيع</b><div className="invoice-meta"><span>رقم الفاتورة: {sale.invoice_number}</span><span>تاريخ الإصدار: {new Date(sale.created_at).toLocaleDateString('ar-EG')}</span></div></header><section className="invoice-party-grid"><div><h3>بيانات البائع</h3><dl>{info('اسم المحطة', sale.seller_station_name || sale.station_owner_name)}{info('الرقم الضريبي', sale.seller_tax_number || sale.tax_number)}{info('رقم السجل التجاري', sale.seller_commercial_registration_number || sale.commercial_registration_number)}{info('رقم التسجيل', sale.seller_registration_number || sale.registration_number)}{info('البريد الإلكتروني', sale.seller_email || sale.email)}{info('رقم الهاتف', sale.seller_phone || sale.phone)}{info('العنوان', sale.seller_address)}</dl></div><div><h3>بيانات المشتري</h3><dl>{info('الاسم', sale.buyer_name)}{info('الرقم الضريبي', sale.buyer_tax_number)}{info('رقم التسجيل', sale.buyer_registration_number)}{info('العنوان', sale.buyer_address)}</dl></div></section><div className="invoice-table-wrap"><table className="invoice-table"><thead><tr><th>اسم الصنف</th><th>كود الصنف</th><th>كود التصنيف</th><th>الوصف</th><th>الكمية / الوحدة</th><th>سعر الوحدة</th><th>قيمة المبيعات</th></tr></thead><tbody>{items.map((entry, index) => <tr key={`${entry.item_code || entry.item_name}-${index}`}><td>{entry.item_name || '—'}</td><td>{entry.item_code || '—'}</td><td>{entry.item_category_code || '—'}</td><td>{entry.item_description || '—'}</td><td>{entry.item_quantity ?? 1} / {entry.item_unit || 'قطعة'}</td><td>{money(entry.item_unit_price)}</td><td>{money(entry.subtotal)}</td></tr>)}</tbody></table></div><div className="invoice-totals"><div><span>إجمالي المبيعات:</span><b>{money(subtotal)}</b></div><div><span>إجمالي الخصم:</span><b>{money(discount)}</b></div><div><span>خصم الفاتورة الإضافي:</span><b>0.00 ج.م</b></div><div className="invoice-net"><span>إجمالي صافي المبلغ:</span><b>{money(net)}</b></div></div><footer>فاتورة إلكترونية مستقلة لا تؤثر على حسابات التشغيل أو المخزون.</footer></article></main></PageLayout>;
}
