import React, { useEffect, useState } from 'react';
import { useRouter } from 'next/router';
import Link from 'next/link';
import PageLayout from '../../../src/components/PageLayout';
import { EmptyState, ErrorState, LoadingState } from '../../../src/components/DataState';
import { Button, PageHeader, SectionCard, StatusBadge } from '../../../src/components/ui';
import { useRequireAuth } from '../../../src/lib/auth';
import { useCurrentStationId } from '../../../src/lib/station';
import supabase from '../../../src/lib/supabaseClient';

const qty = (value: number) => `${Number(value || 0).toLocaleString('ar-EG', { maximumFractionDigits: 2 })} لتر`;
const money = (value: number) => `${Number(value || 0).toLocaleString('ar-EG', { maximumFractionDigits: 2 })} ج.م`;
const movementLabel: Record<string, string> = { sale: 'بيع', delivery: 'توريد', adjustment: 'تسوية', variance_writeoff: 'خصم فرق', reversal: 'إلغاء' };
export default function TankDetails() {
  const router = useRouter(); const { user } = useRequireAuth(); const stationId = useCurrentStationId(user?.id ?? null); const tankId = typeof router.query.id === 'string' ? router.query.id : '';
  const [tank, setTank] = useState<any>(null); const [deliveries, setDeliveries] = useState<any[]>([]); const [sales, setSales] = useState<any[]>([]); const [movements, setMovements] = useState<any[]>([]); const [meters, setMeters] = useState<any[]>([]); const [state, setState] = useState<'loading' | 'ready' | 'error'>('loading');
  useEffect(() => { if (!tankId || !stationId) return; (async () => { setState('loading'); const [tankResult, deliveryResult, salesResult, movementResult, meterResult] = await Promise.all([supabase.from('v_tank_status').select('*').eq('station_id', stationId).eq('tank_id', tankId).maybeSingle(), supabase.from('v_deliveries').select('*').eq('station_id', stationId).eq('tank_id', tankId).eq('status', 'active').order('business_date', { ascending: false }).limit(20), supabase.from('v_sales').select('*').eq('station_id', stationId).eq('tank_id', tankId).eq('status', 'active').order('business_date', { ascending: false }).limit(20), supabase.from('v_ledger_feed').select('*').eq('station_id', stationId).eq('tank_id', tankId).order('occurred_at', { ascending: false }).limit(100), supabase.from('pump_meters').select('id,code,name').eq('station_id', stationId).eq('tank_id', tankId).eq('is_active', true)]); if (tankResult.error || deliveryResult.error || salesResult.error || movementResult.error || meterResult.error) { setState('error'); return; } setTank(tankResult.data); setDeliveries(deliveryResult.data || []); setSales(salesResult.data || []); setMovements(movementResult.data || []); setMeters(meterResult.data || []); setState('ready'); })(); }, [stationId, tankId]);
  return <PageLayout title="تفاصيل الخزان"><main dir="rtl">{state === 'loading' ? <LoadingState /> : state === 'error' ? <ErrorState onRetry={() => router.reload()} /> : !tank ? <EmptyState title="الخزان غير موجود" description="تحقق من الرابط أو عد إلى مركز الوقود." /> : <><PageHeader eyebrow="مركز الوقود" title={`${tank.tank_code} · ${tank.tank_name}`} description={`${tank.fuel_code} · ${tank.fuel_name}`} actions={<Link className="ui-button secondary" href="/fuel">العودة إلى الوقود</Link>} /><div className="stats-grid"><article className="stat-card stat-success"><span>المخزون الحالي</span><strong>{qty(tank.system_quantity)}</strong><small>من {qty(tank.capacity)}</small></article><article className="stat-card stat-brand"><span>نسبة الامتلاء</span><strong>{Number(tank.fill_pct || 0).toLocaleString('ar-EG')}%</strong><small>المتاح للضخ {qty(tank.available_quantity)}</small></article><article className="stat-card stat-warning"><span>العدادات</span><strong>{meters.length * 2}</strong><small>{meters.length} عداد × قراءتين للجلسة</small></article><article className="stat-card stat-brand"><span>آخر حركة</span><strong>{tank.last_movement_at ? new Date(tank.last_movement_at).toLocaleDateString('ar-EG') : '—'}</strong><small>{tank.status === 'operational' ? 'تشغيلي' : 'غير متاح'}</small></article></div><SectionCard title="مستوى الخزان"><div className="fuel-level large"><span style={{ width: `${Math.min(Math.max(Number(tank.fill_pct || 0), 0), 100)}%` }} /></div><div className="fuel-tank-values"><b>{qty(tank.system_quantity)}</b><span>الحد الآمن {qty(tank.min_safe_level)} · المتاح {qty(tank.available_quantity)}</span></div></SectionCard><SectionCard title="آخر التوريدات"><DataTable rows={deliveries} empty="لا توجد توريدات مرتبطة بهذا الخزان." headers={['التاريخ', 'المورد', 'الكمية', 'السعر', 'الإجمالي']} render={(row) => <><td>{row.business_date}</td><td>{row.supplier_name || '—'}</td><td>{qty(row.quantity)}</td><td>{money(row.unit_cost)}</td><td>{money(row.total_cost)}</td></>} /></SectionCard><SectionCard title="آخر المبيعات"><DataTable rows={sales} empty="لا توجد مبيعات مرتبطة بهذا الخزان." headers={['التاريخ', 'العميل', 'الكمية', 'السعر', 'الإجمالي']} render={(row) => <><td>{row.business_date}</td><td>{row.customer_name || '—'}</td><td>{qty(row.quantity)}</td><td>{money(row.unit_price)}</td><td>{money(row.gross_amount)}</td></>} /></SectionCard><SectionCard title="سجل حركة الخزان"><DataTable rows={movements} empty="لا توجد حركة مسجلة." headers={['التاريخ والوقت', 'الحركة', 'الكمية', 'الرصيد بعد', 'المستخدم']} render={(row) => <><td>{row.business_date}<small className="block">{row.occurred_at ? new Date(row.occurred_at).toLocaleTimeString('ar-EG') : '—'}</small></td><td><StatusBadge tone={row.quantity_delta >= 0 ? 'success' : 'info'}>{movementLabel[row.txn_type] || row.txn_type}</StatusBadge></td><td>{qty(row.quantity_delta)}</td><td>{qty(row.running_balance)}</td><td>{row.created_by_name || '—'}</td></>} /></SectionCard></>}</main></PageLayout>;
}
function DataTable({ rows, empty, headers, render }: { rows: any[]; empty: string; headers: string[]; render: (row: any) => React.ReactNode }) { return rows.length ? <div className="table-scroll"><table className="data-table"><thead><tr>{headers.map((header) => <th key={header}>{header}</th>)}</tr></thead><tbody>{rows.map((row) => <tr key={row.id}>{render(row)}</tr>)}</tbody></table></div> : <EmptyState title={empty} description="" />; }
