import React, { useState } from 'react';
import { useRouter } from 'next/router';
import PageLayout from '../../src/components/PageLayout';
import FormField from '../../src/components/FormField';
import { useRequireAuth } from '../../src/lib/auth';
import { useCurrentStationId } from '../../src/lib/station';
import supabase from '../../src/lib/supabaseClient';

const types = [['car_wash', 'غسيل سيارة'], ['oil_change', 'تغيير زيت'], ['carpet_wash', 'غسيل سجاد'], ['blanket_wash', 'غسيل بطانية'], ['other', 'أخرى']];
export default function NewService() {
  const { user } = useRequireAuth(); const router = useRouter(); const stationId = useCurrentStationId(user?.id ?? null);
  const [type, setType] = useState('car_wash'); const [name, setName] = useState(''); const [vehicle, setVehicle] = useState(''); const [amount, setAmount] = useState(''); const [message, setMessage] = useState(''); const [saving, setSaving] = useState(false);
  async function submit(event: React.FormEvent) { event.preventDefault(); setMessage(''); const value = Number(amount); if (!stationId) return setMessage('لا توجد محطة مرتبطة بهذا الحساب.'); if (!Number.isFinite(value) || value <= 0) return setMessage('المبلغ يجب أن يكون رقمًا أكبر من صفر.'); if (type === 'other' && !name.trim()) return setMessage('اكتب اسم الخدمة عند اختيار أخرى.'); setSaving(true); try { const { data: authData } = await supabase.auth.getSession(); const response = await fetch('/api/services/create', { method: 'POST', headers: { 'Content-Type': 'application/json', ...(authData.session?.access_token ? { Authorization: `Bearer ${authData.session.access_token}` } : {}) }, body: JSON.stringify({ station_id: stationId, service_type: type, service_name: type === 'other' ? name : null, vehicle_type: vehicle, amount: value, operator_id: user?.id }) }); const body = await response.json(); if (!response.ok) throw new Error(body.error || 'تعذر إضافة الخدمة.'); await router.push(`/services/${body.service?.id}?autoPrint=1`); } catch (error: any) { setMessage(error.message || 'تعذر إضافة الخدمة.'); } finally { setSaving(false); } }
  return <PageLayout title="إضافة خدمة"><main dir="rtl" className="page-shell"><div className="page-heading"><div><span className="eyebrow">الخدمات</span><h2>إضافة خدمة</h2><p>تُحفظ الخدمة داخل الجلسة المفتوحة الحالية فقط.</p></div></div><form onSubmit={submit} className="ui-card max-w-xl space-y-4"><FormField label="نوع الخدمة"><select required value={type} onChange={(event) => setType(event.target.value)} className="w-full border rounded px-3 py-2">{types.map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></FormField>{type === 'other' && <FormField label="اسم الخدمة"><input required value={name} onChange={(event) => setName(event.target.value)} className="w-full border rounded px-3 py-2" placeholder="اكتب اسم الخدمة" /></FormField>}<FormField label="نوع السيارة"><input value={vehicle} onChange={(event) => setVehicle(event.target.value)} className="w-full border rounded px-3 py-2" placeholder="مثال: سيدان أو لا ينطبق" /></FormField><FormField label="المبلغ"><input required min="0.01" step="0.01" type="number" value={amount} onChange={(event) => setAmount(event.target.value)} className="w-full border rounded px-3 py-2" placeholder="0.00" /></FormField><div className="flex gap-3"><button disabled={saving} className="ui-button">{saving ? 'جارٍ التنفيذ…' : 'تنفيذ / إضافة الخدمة'}</button><button type="button" className="ui-button secondary" onClick={() => router.push('/services')}>إلغاء</button></div>{message && <p className="text-sm text-red-600">{message}</p>}</form></main></PageLayout>;
}
