import React, { useEffect, useState } from 'react';
import { useRouter } from 'next/router';
import PageLayout from '../../src/components/PageLayout';
import { Button, PageHeader, SectionCard } from '../../src/components/ui';
import { useToast } from '../../src/components/ToastProvider';
import { useRequireAuth } from '../../src/lib/auth';
import { useCurrentStationId } from '../../src/lib/station';

const cairoDate = () => new Intl.DateTimeFormat('en-CA', { timeZone: 'Africa/Cairo', year: 'numeric', month: '2-digit', day: '2-digit' }).format(new Date());

export default function NewSale() {
  const { user } = useRequireAuth(); const router = useRouter(); const stationId = useCurrentStationId(user?.id ?? null); const { notify } = useToast();
  const [tanks, setTanks] = useState<any[]>([]); const [form, setForm] = useState({ tank_id: '', business_date: cairoDate(), quantity: '' }); const [saving, setSaving] = useState(false); const [error, setError] = useState('');
  useEffect(() => { if (!stationId) return setTanks([]); fetch(`/api/tanks?stationId=${encodeURIComponent(stationId)}`).then((r) => r.json()).then((d) => setTanks(d.tanks || [])).catch(() => setTanks([])); }, [stationId]);
  const selectedTank = tanks.find((tank) => tank.tank_id === form.tank_id);
  async function submit(event: React.FormEvent) { event.preventDefault(); setError(''); const quantity = Number(form.quantity); if (!stationId || !form.tank_id || !form.business_date || !Number.isFinite(quantity) || quantity <= 0) return setError('أكمل الخزان والتاريخ والكمية الصحيحة قبل الحفظ.'); setSaving(true); try { const response = await fetch('/api/sales/create', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ station_id: stationId, tank_id: form.tank_id, fuel_type_id: selectedTank?.fuel_type_id, business_date: form.business_date, quantity }) }); const body = await response.json(); if (!response.ok) throw new Error(body.error || 'تعذر تسجيل عملية البيع.'); notify('تم تسجيل عملية البيع بنجاح.'); await router.push('/sales'); } catch (reason: any) { setError(reason.message || 'حدث خطأ أثناء حفظ العملية. حاول مرة أخرى.'); } finally { setSaving(false); } }
  return <PageLayout title="تسجيل بيع"><PageHeader eyebrow="المبيعات" title="تسجيل عملية بيع" description="سجّل الكمية بسرعة داخل الوردية المفتوحة الحالية." actions={<Button variant="secondary" type="button" onClick={() => router.push('/sales')}>العودة للسجل</Button>}/><SectionCard title="بيانات العملية" description="ترتبط العملية تلقائيًا بالوردية المفتوحة للتاريخ المحدد." className="max-w-2xl"><form onSubmit={submit} noValidate><div className="form-grid"><div className="form-field"><label htmlFor="sale-tank">الخزان <span aria-hidden="true">*</span></label><select id="sale-tank" required value={form.tank_id} onChange={(event) => setForm({ ...form, tank_id: event.target.value })}><option value="">اختر الخزان والوقود</option>{tanks.map((tank) => <option key={tank.tank_id} value={tank.tank_id}>{tank.tank_code} — {tank.fuel_name}</option>)}</select>{selectedTank && <small>الرصيد المتاح: {Number(selectedTank.available_quantity ?? selectedTank.system_quantity ?? 0).toLocaleString('ar-EG')} لتر</small>}</div><div className="form-field"><label htmlFor="sale-date">تاريخ العملية <span aria-hidden="true">*</span></label><input id="sale-date" required type="date" value={form.business_date} onChange={(event) => setForm({ ...form, business_date: event.target.value })}/><small>يجب أن يطابق تاريخ الوردية المفتوحة.</small></div><div className="form-field form-field-full"><label htmlFor="sale-quantity">الكمية باللتر <span aria-hidden="true">*</span></label><input id="sale-quantity" required min="0.001" step="0.001" inputMode="decimal" type="number" autoFocus value={form.quantity} onChange={(event) => setForm({ ...form, quantity: event.target.value })} placeholder="مثال: 50"/></div></div>{error && <p className="form-error" role="alert">{error}</p>}<div className="form-actions"><Button type="submit" loading={saving}>حفظ عملية البيع</Button><Button type="button" variant="secondary" disabled={saving} onClick={() => router.push('/sales')}>إلغاء</Button></div></form></SectionCard></PageLayout>;
}
