import React, { useCallback, useEffect, useState } from 'react';
import { useRouter } from 'next/router';
import PageLayout from '../../src/components/PageLayout';
import { useRequireAuth } from '../../src/lib/auth';

const messageFrom = (data: any, fallback: string) => data?.error || data?.message || data?.hint || fallback;

export default function SessionPage() {
  const router = useRouter(); useRequireAuth(); const sessionId = typeof router.query.sessionId === 'string' ? router.query.sessionId : '';
  const [session, setSession] = useState<any>(null); const [lines, setLines] = useState<any[]>([]); const [cashByFuel, setCashByFuel] = useState<any[]>([]); const [message, setMessage] = useState(''); const [loadError, setLoadError] = useState(''); const [submitting, setSubmitting] = useState(false);
  const load = useCallback(async () => { if (!sessionId) return; setLoadError(''); try { const response = await fetch(`/api/reconciliation/detail?sessionId=${encodeURIComponent(sessionId)}`); const data = await response.json().catch(() => ({})); if (!response.ok) throw new Error(messageFrom(data, 'تعذر تحميل تفاصيل الجلسة.')); setSession(data.session); setLines(data.lines || []); setCashByFuel(data.cashByFuel || []); } catch (error: any) { setLoadError(error.message || 'تعذر الاتصال بالخادم.'); } }, [sessionId]);
  useEffect(() => { load(); }, [load]);
  async function submit() { if (!session?.id) return setMessage('معرّف جلسة التسوية غير صالح. أعد فتح الصفحة.'); setSubmitting(true); setMessage(''); try { const response = await fetch('/api/reconciliation/submit', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ session_id: session.id }) }); const data = await response.json().catch(() => ({})); if (!response.ok) { console.error('Reconciliation submit error:', { status: response.status, data, session_id: session.id }); setMessage(messageFrom(data, 'تعذر إغلاق الجلسة.')); return; } await router.replace('/reconciliation'); } catch { setMessage('حدث خطأ في الاتصال بالخادم أثناء إغلاق الجلسة.'); } finally { setSubmitting(false); } }
  if (loadError) return <PageLayout title="التسوية"><div className="empty-state"><h3>تعذر فتح الجلسة</h3><p>{loadError}</p><button className="ui-button mt-5" onClick={load}>إعادة المحاولة</button></div></PageLayout>;
  if (!session) return <PageLayout title="التسوية"><div className="empty-state"><p>جارٍ تحميل الجلسة…</p></div></PageLayout>;
  const isOpen = session.status === 'open';
  return <PageLayout title={`التسوية ${session.business_date}`}><main className="reconciliation-page" dir="rtl"><div className="page-heading"><div><span className="eyebrow">جلسة التسوية</span><h2>{session.business_date} · {session.shift_code || 'وردية'}</h2><p>الحسابات تتحدث تلقائياً مع كل بيع أو قراءة من الكنترول.</p></div><button className="ui-button secondary" onClick={load}>تحديث</button></div>{!isOpen && <div className="notice notice-warning">هذه الجلسة مغلقة وتم تثبيت حساباتها، وهي متاحة للمراجعة فقط.</div>}<section className="ui-card p-5 mb-5"><div className="flex items-center justify-between gap-4"><div><b>إجمالي المبالغ المحصلة</b><p className="mt-1 text-sm text-[var(--text-muted)]">تشمل مبيعات هذه الجلسة فقط.</p></div><strong className="text-2xl text-[var(--text-heading)]">{Number(session.total_collected || 0).toLocaleString('ar-EG')} ج.م</strong></div><div className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{cashByFuel.length ? cashByFuel.map((fuel) => <div key={fuel.fuel_type_id} className="rounded-xl bg-[var(--surface-soft)] p-3"><b>{fuel.fuel_name}</b><small className="block mt-1 text-[var(--text-muted)]">{Number(fuel.quantity).toLocaleString('ar-EG')} لتر مباع</small><strong className="block mt-2">{Number(fuel.collected).toLocaleString('ar-EG')} ج.م</strong></div>) : <small className="text-[var(--text-muted)]">لا توجد مبيعات مسجلة داخل هذه الجلسة.</small>}</div></section><div className="space-y-3">{lines.map((line) => <ReconciliationLine key={line.id} line={line} sessionId={session.id} onSaved={load} disabled={!isOpen} />)}</div><div className="mt-6 text-right">{isOpen && <button className="ui-button" disabled={submitting} onClick={submit}>{submitting ? 'جارٍ الإغلاق…' : 'إغلاق الجلسة وتثبيت الحساب'}</button>}{message && <p className="mt-3 text-sm text-red-600">{message}</p>}</div></main></PageLayout>;
}

function ReconciliationLine({ line, sessionId, onSaved, disabled }: { line: any; sessionId: string; onSaved: () => void; disabled: boolean }) {
  const [value, setValue] = useState(line.actual_closing_qty == null ? '' : String(line.actual_closing_qty)); const [saving, setSaving] = useState(false); const [error, setError] = useState('');
  async function save() { const quantity = Number(value); const capacity = Number(line.capacity || 0); if (!sessionId || !line.tank_id || !Number.isFinite(quantity) || quantity < 0) return setError('أدخل كمية فعلية صحيحة تساوي صفراً أو أكثر.'); if (capacity > 0 && quantity > capacity) return setError(`الكمية لا يمكن أن تتجاوز سعة الخزان (${capacity.toLocaleString('ar-EG')} لتر).`); setSaving(true); setError(''); const payload = { session_id: sessionId, tank_id: line.tank_id, actual_closing_qty: quantity }; console.debug('Reconciliation measurement payload:', payload); try { const response = await fetch('/api/reconciliation/record', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(payload) }); const data = await response.json().catch(() => ({})); if (response.ok) { await onSaved(); } else { console.error('Reconciliation record error:', { status: response.status, data, payload }); setError(messageFrom(data, 'تعذر حفظ قراءة الخزان.')); } } catch { setError('حدث خطأ في الاتصال بالخادم.'); } finally { setSaving(false); } }
  return <div className="ui-card p-4 text-right"><div className="flex items-center justify-between gap-3"><div><b>{line.tank_code} — {line.fuel_name}</b><p className="mt-1 text-sm text-[var(--text-muted)]">المتوقع: {line.expected_closing_qty} لتر · سعة الخزان: {line.capacity} لتر · الفرق: {line.variance_qty ?? '—'}</p></div><div className="flex gap-2"><input disabled={disabled} type="number" min="0" max={line.capacity} value={value} onChange={(event) => setValue(event.target.value)} className="w-36 rounded border px-3 py-2 text-right" placeholder="الكمية الفعلية" /><button onClick={save} disabled={disabled || saving || value === ''} className="ui-button">{saving ? 'جارٍ الحفظ…' : 'حفظ'}</button></div></div>{error && <p className="mt-2 text-sm text-red-600">{error}</p>}</div>;
}
