import React, { useCallback, useEffect, useMemo, useState } from 'react';
import PageLayout from '../../src/components/PageLayout';
import { EmptyState, ErrorState, LoadingState } from '../../src/components/DataState';
import { useRequireAuth, useRole } from '../../src/lib/auth';
import { useCurrentStationId } from '../../src/lib/station';
import supabase from '../../src/lib/supabaseClient';
import { serviceTypeLabel, shiftLabel } from '../../src/lib/displayLabels';

type Row = { fuel_type_id?: string; fuel_code?: string; fuel_name?: string; delivered?: number; sold?: number; meter_sold?: number; variance?: number; variance_expense?: number; adjusted?: number; movement_count?: number; revenue?: number; registered_revenue?: number; meter_revenue?: number; procurement_cost?: number; cost?: number; profit?: number; average_sale_price?: number; average_purchase_price?: number; net_change?: number };
type Service = { id: string; service_type?: string; service_name?: string; vehicle_type?: string; amount?: number; business_date?: string; created_at?: string };
type Expense = { id: string; business_date?: string; category?: string; description?: string; amount?: number };
type SessionSummary = { id: string; business_date?: string; shift_code?: string; shift_name?: string; shift_seq?: number; status?: string; opened_at?: string; submitted_at?: string; total_sold?: number; total_actual?: number; total_variance?: number; total_collected?: number };
type Totals = { collected: number; cost: number; procurement_cost?: number; variance_expense?: number; expense_total?: number; profit: number; service_total?: number; service_count?: number };
type MovementTotals = { delivered: number; sold: number; variance: number };
const today = () => {
  const parts = new Intl.DateTimeFormat('en-CA', { timeZone: 'Africa/Cairo', year: 'numeric', month: '2-digit', day: '2-digit' })
    .formatToParts(new Date()).reduce((result, part) => ({ ...result, [part.type]: part.value }), {} as Record<string, string>);
  return `${parts.year}-${parts.month}-${parts.day}`;
};
const money = (value: number) => `${Number(value || 0).toLocaleString('ar-EG', { maximumFractionDigits: 2 })} ج.م`;
const litres = (value: number) => `${Number(value || 0).toLocaleString('ar-EG', { maximumFractionDigits: 2 })} لتر`;

export default function DailyReport() {
  const { user } = useRequireAuth(); const stationId = useCurrentStationId(user?.id ?? null);
  const [rows, setRows] = useState<Row[]>([]); const [from, setFrom] = useState(today); const [to, setTo] = useState(today); const [totals, setTotals] = useState<Totals>({ collected: 0, cost: 0, procurement_cost: 0, variance_expense: 0, profit: 0, service_total: 0, service_count: 0 }); const [state, setState] = useState<'loading'|'ready'|'error'>('loading'); const [message, setMessage] = useState('');
  const [services, setServices] = useState<Service[]>([]); const [expenses, setExpenses] = useState<Expense[]>([]); const [sessions, setSessions] = useState<SessionSummary[]>([]); const [meterSales, setMeterSales] = useState<any[]>([]); const [sessionId, setSessionId] = useState('');
  const { role } = useRole(); const [resetOpen, setResetOpen] = useState(false); const [resetScope, setResetScope] = useState<'operational' | 'sessions'>('operational'); const [resetPassword, setResetPassword] = useState(''); const [resetCode, setResetCode] = useState(''); const [resetting, setResetting] = useState(false); const [resetError, setResetError] = useState('');
  const load = useCallback(async () => { if (!stationId) return; if (from > to) { setMessage('تاريخ البداية يجب أن يسبق تاريخ النهاية.'); return; } setMessage(''); setState('loading'); try { const { data: authData } = await supabase.auth.getSession(); const headers: HeadersInit = authData.session?.access_token ? { Authorization: `Bearer ${authData.session.access_token}` } : {}; const params = new URLSearchParams({ stationId, from, to }); if (sessionId) params.set('sessionId', sessionId); const response = await fetch(`/api/reports/daily?${params.toString()}`, { headers }); const data = await response.json(); if (!response.ok) throw new Error(data.error); setRows(data.rows || []); setServices(data.services || []); setExpenses(data.expenses || []); setSessions(data.sessions || []); setMeterSales(data.meterSales || []); setTotals(data.totals || { collected: 0, cost: 0, expense_total: 0, profit: 0, service_total: 0, service_count: 0 }); setState('ready'); } catch { setState('error'); } }, [stationId, from, to, sessionId]);
  useEffect(() => { if (stationId) load(); }, [stationId, load]);
  async function resetOperationalData() {
    if (!stationId || !resetPassword || !resetCode) { setResetError('أدخل كلمة المرور وكود المحطة.'); return; }
    setResetting(true); setResetError('');
    try {
      const { data: authData } = await supabase.auth.getSession();
      const headers: HeadersInit = { 'Content-Type': 'application/json' };
      if (authData.session?.access_token) headers.Authorization = `Bearer ${authData.session.access_token}`;
      const response = await fetch('/api/reports/reset-data', { method: 'POST', headers, body: JSON.stringify({ station_id: stationId, station_code: resetCode, password: resetPassword, scope: resetScope }) });
      const data = await response.json().catch(() => ({}));
      if (!response.ok) throw new Error(data.error || (response.status === 409 ? 'أغلق جميع الورديات المفتوحة قبل حذف بيانات التشغيل.' : 'تعذر حذف بيانات التشغيل.'));
      setRows([]); setServices([]); setExpenses([]); setSessions([]); setMeterSales([]); setTotals({ collected: 0, cost: 0, procurement_cost: 0, variance_expense: 0, expense_total: 0, profit: 0, service_total: 0, service_count: 0 }); setResetOpen(false); setResetPassword(''); setResetCode(''); setMessage(resetScope === 'sessions' ? 'تم مسح الجلسات والبيانات غير الأساسية مع إبقاء العمليات.' : 'تم مسح التطبيق بالكامل مع إبقاء المحطة وحسابات الدخول والإعدادات الأساسية.');
    } catch (error: any) { setResetError(error.message || 'تعذر حذف بيانات التشغيل.'); }
    finally { setResetting(false); }
  }
  const movementTotals = useMemo<MovementTotals>(() => rows.reduce<MovementTotals>((all, row) => ({ delivered: all.delivered + Number(row.delivered || 0), sold: all.sold + Number(row.sold || 0), variance: all.variance + Number(row.variance || 0) }), { delivered: 0, sold: 0, variance: 0 }), [rows]);
  const meterSalesTotal = useMemo(() => meterSales.reduce((total, line) => total + Number(line.meter_sold_qty || 0), 0), [meterSales]);
  return <PageLayout title="التقارير"><div className="report-page">
    <div className="page-heading print-title"><div><h2>تقرير حركة الوقود</h2><p>تحليل شامل للمبيعات والتوريدات والأرباح خلال فترة محددة.</p></div><div className="flex gap-2 no-print"><button className="ui-button secondary" onClick={() => window.print()}>طباعة التقرير</button>{role === 'manager' && <><button className="ui-button secondary text-red-600" onClick={() => { setResetScope('sessions'); setResetError(''); setResetOpen(true); }}>مسح الجلسات</button><button className="ui-button secondary text-red-600" onClick={() => { setResetScope('operational'); setResetError(''); setResetOpen(true); }}>مسح كامل التطبيق</button></>}</div></div>
    {resetOpen && <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/50 p-4 no-print"><section className="ui-card w-full max-w-lg p-6 text-right" role="dialog" aria-modal="true" aria-labelledby="reset-data-title"><h3 id="reset-data-title">{resetScope === 'sessions' ? 'مسح الجلسات والبيانات غير الأساسية' : 'مسح كامل التطبيق'}</h3><p className="mt-2 text-sm text-red-600">{resetScope === 'sessions' ? 'سيتم حذف الجلسات والمصروفات والخدمات والتسويات والتنبيهات، مع إبقاء المبيعات والتوريدات.' : 'سيتم حذف الخزانات وأنواع الوقود والموردين والعملاء والمبيعات والتوريدات والمخزون والجلسات وكل البيانات التشغيلية. ستبقى المحطة وحسابات الدخول والإعدادات الأساسية. يجب إغلاق كل وردية أولاً.'}</p><div className="mt-4 space-y-3"><div className="form-field"><label>كلمة المرور الحالية</label><input type="password" autoComplete="current-password" value={resetPassword} onChange={(event) => setResetPassword(event.target.value)} /></div><div className="form-field"><label>اكتب كود المحطة للتأكيد</label><input value={resetCode} onChange={(event) => setResetCode(event.target.value)} placeholder="كود المحطة" /></div></div>{resetError && <p className="mt-3 text-sm text-red-600">{resetError}</p>}<div className="mt-5 flex justify-end gap-2"><button className="ui-button secondary" onClick={() => setResetOpen(false)} disabled={resetting}>إلغاء</button><button className="ui-button bg-red-600 text-white" onClick={resetOperationalData} disabled={resetting || !resetPassword || !resetCode}>{resetting ? 'جارٍ الحذف…' : 'تأكيد حذف البيانات'}</button></div></section></div>}
    <section className="ui-card report-filter no-print"><div className="form-field"><label>من تاريخ</label><input type="date" value={from} onChange={(e) => setFrom(e.target.value)} /></div><div className="form-field"><label>إلى تاريخ</label><input type="date" value={to} onChange={(e) => setTo(e.target.value)} /></div><div className="form-field"><label>الجلسة</label><select value={sessionId} onChange={(e) => setSessionId(e.target.value)}><option value="">كل الجلسات</option>{sessions.map((session) => <option key={session.id} value={session.id}>{session.business_date || '—'} · {shiftLabel(session.shift_name, session.shift_code, session.shift_seq)}</option>)}</select></div><button className="ui-button" onClick={load}>عرض التقرير</button>{message && <small className="text-red-600">{message}</small>}</section>
    <p className="report-period">الفترة: {from} — {to}</p><p className="report-period">مبيعات العدادات: {litres(meterSalesTotal)} · المصروفات المعتمدة: {money(Number(totals.expense_total || 0))} · لا تؤثر المعلّقة أو المرفوضة على الربح.</p>
    <section className="report-kpis"><article><small>إجمالي التوريدات</small><b>{litres(movementTotals.delivered)}</b><span>حركة داخلة للمخزون</span></article><article><small>المبيعات المسجلة</small><b>{litres(movementTotals.sold)}</b><span>عمليات البيع المالي</span></article><article><small>مبيعات العدادات</small><b>{litres(meterSalesTotal)}</b><span>الإجمالي الفعلي دون تكرار</span></article><article><small>إجمالي المحصل</small><b>{money(totals.collected)}</b><span>المسجل + الجزء غير المسجل + الخدمات</span></article><article><small>تكلفة المبيعات</small><b>{money(totals.cost)}</b><span>تكلفة الكمية الفعلية المباعة</span></article><article><small>قيمة التوريدات</small><b>{money(Number(totals.procurement_cost || 0))}</b><span>شراء المخزون خلال الفترة</span></article><article className="report-profit"><small>صافي الربح</small><b className={totals.profit < 0 ? 'text-red-600' : ''}>{money(totals.profit)}</b><span>الإيراد − تكلفة المبيعات</span></article></section>
    <section className="ui-card report-table"><div className="ui-toolbar"><div><b>الأداء المالي وحركة المخزون حسب الوقود</b><small className="block mt-1 text-[var(--text-muted)]">الإيراد يجمع المبيعات المسجلة والجزء غير المسجل من مبيعات العداد مرة واحدة فقط.</small></div><span className="status-badge">{rows.length} نوع وقود</span></div>{state === 'loading' ? <LoadingState /> : state === 'error' ? <ErrorState onRetry={load} /> : rows.length === 0 ? <EmptyState title="لا توجد حركة خلال هذه الفترة" description="غيّر الفترة أو أضف عمليات بيع وتوريد." /> : <div className="table-scroll"><table className="data-table financial-table"><thead><tr><th>الوقود</th><th>توريد / بيع</th><th>مبيعات العداد</th><th>الإيراد المسجل</th><th>إيراد العداد الإضافي</th><th>تكلفة المبيعات</th><th>صافي الربح</th></tr></thead><tbody>{rows.map((row) => <tr key={row.fuel_type_id || row.fuel_code}><td><b>{row.fuel_name || '—'}</b><small className="block mt-1 text-[var(--text-muted)]">{row.fuel_code || '—'} · {Number(row.movement_count || 0)} حركة</small></td><td><b>{litres(Number(row.delivered))}</b><small className="block mt-1 text-[var(--text-muted)]">مسجل: {litres(Number(row.sold))}</small></td><td className="font-bold">{litres(Number(row.meter_sold))}</td><td>{money(Number(row.registered_revenue))}</td><td>{money(Number(row.meter_revenue))}</td><td>{money(Number(row.cost))}</td><td className={Number(row.profit) < 0 ? 'text-red-600 font-bold' : 'text-emerald-700 font-bold'}>{money(Number(row.profit))}</td></tr>)}</tbody><tfoot><tr><td>الإجمالي</td><td>{litres(movementTotals.delivered)}<small className="block">مسجل: {litres(movementTotals.sold)}</small></td><td>{litres(meterSalesTotal)}</td><td>{money(rows.reduce((total, row) => total + Number(row.registered_revenue || 0), 0))}</td><td>{money(rows.reduce((total, row) => total + Number(row.meter_revenue || 0), 0))}</td><td>{money(totals.cost)}</td><td>{money(totals.profit)}</td></tr></tfoot></table></div>}</section>
    <section className="ui-card report-table"><div className="ui-toolbar"><div><b>تفاصيل سحب العدادات</b><small className="block mt-1 text-[var(--text-muted)]">السحب محسوب من مجموع فروق عدادات كل خزان، دون إنشاء مبيعات إضافية.</small></div><span className="status-badge">{meterSales.length} خزان</span></div>{meterSales.length === 0 ? <EmptyState title="لا توجد قراءات عدادات" description="ستظهر تفاصيل السحب بعد إغلاق جلسة." /> : <div className="table-scroll"><table className="data-table"><thead><tr><th>التاريخ</th><th>الخزان</th><th>عدد العدادات</th><th>إجمالي السحب</th><th>المبيعات المسجلة</th><th>الفرق</th></tr></thead><tbody>{meterSales.map((line: any) => <tr key={line.id}><td>{line.business_date || '—'}</td><td><b>{line.tank_code || line.fuel_name || '—'}</b></td><td>{line.meter_readings_count || '—'}</td><td>{litres(Number(line.meter_sold_qty))}</td><td>{litres(Number(line.sold_qty))}</td><td>{litres(Number(line.variance_qty))}</td></tr>)}</tbody></table></div>}</section>
    <section className="ui-card report-table"><div className="ui-toolbar"><div><b>المصروفات المعتمدة</b><small className="block mt-1 text-[var(--text-muted)]">المصروفات المعتمدة فقط تخصم من صافي الربح.</small></div><span className="status-badge">{expenses.length} مصروف</span></div>{expenses.length === 0 ? <EmptyState title="لا توجد مصروفات معتمدة" description="المصروفات المعلقة أو المرفوضة لا تؤثر في التقرير." /> : <div className="table-scroll"><table className="data-table"><thead><tr><th>التاريخ</th><th>التصنيف</th><th>الوصف</th><th>المبلغ</th></tr></thead><tbody>{expenses.map((expense) => <tr key={expense.id}><td>{expense.business_date || '—'}</td><td>{expense.category || '—'}</td><td>{expense.description || '—'}</td><td className="font-bold">{money(Number(expense.amount))}</td></tr>)}</tbody></table></div>}</section>
    <section className="ui-card report-table"><div className="ui-toolbar"><div><b>الخدمات المنفذة</b><small className="block mt-1 text-[var(--text-muted)]">خدمات الفترة المختارة، مضافة إلى إجمالي الدخل والربح.</small></div><span className="status-badge">{services.length} خدمة</span></div>{services.length === 0 ? <EmptyState title="لا توجد خدمات خلال هذه الفترة" description="ستظهر الخدمات هنا بعد تنفيذها." /> : <div className="table-scroll"><table className="data-table"><thead><tr><th>الخدمة</th><th>نوع السيارة</th><th>التاريخ والوقت</th><th>المبلغ</th></tr></thead><tbody>{services.map((service) => <tr key={service.id}><td><b>{service.service_name || serviceTypeLabel(service.service_type)}</b></td><td>{service.vehicle_type || 'لا ينطبق'}</td><td>{service.created_at ? new Date(service.created_at).toLocaleString('ar-EG') : service.business_date || '—'}</td><td>{money(Number(service.amount))}</td></tr>)}</tbody></table></div>}</section>
    <section className="ui-card report-table report-sessions"><div className="ui-toolbar"><div><b>نتائج الورديات والجلسات</b><small className="block mt-1 text-[var(--text-muted)]">ملخص كل وردية ضمن الفترة المختارة، بما في ذلك المبيعات والفرق وحالة الإغلاق.</small></div><span className="status-badge">{sessions.length} جلسة</span></div>{sessions.length === 0 ? <EmptyState title="لا توجد ورديات في هذه الفترة" description="ستظهر نتائج الجلسة هنا بعد فتح وردية ضمن الفترة المختارة." /> : <div className="table-scroll"><table className="data-table"><thead><tr><th>التاريخ</th><th>الوردية</th><th>المبيعات</th><th>القراءة الفعلية</th><th>الفرق</th><th>الحالة</th></tr></thead><tbody>{sessions.map((session) => <tr key={session.id}><td>{session.business_date || '—'}</td><td><b>{shiftLabel(session.shift_name, session.shift_code, session.shift_seq)}</b></td><td>{litres(Number(session.total_sold))}</td><td>{litres(Number(session.total_actual))}</td><td className={Number(session.total_variance) < 0 ? 'text-red-600 font-bold' : 'font-bold'}>{litres(Number(session.total_variance))}</td><td><span className={`status-badge ${session.status === 'submitted' ? 'status-success' : 'status-warning'}`}>{session.status === 'submitted' ? 'مغلقة' : 'مفتوحة'}</span></td></tr>)}</tbody></table></div>}</section>
  </div></PageLayout>;
}
