import React, { useCallback, useEffect, useMemo, useState } from 'react';
import PageLayout from '../../src/components/PageLayout';
import { EmptyState, ErrorState, LoadingState } from '../../src/components/DataState';
import { useRequireAuth } from '../../src/lib/auth';
import { useCurrentStationId } from '../../src/lib/station';

type Row = { fuel_type_id?: string; fuel_code?: string; fuel_name?: string; delivered?: number; sold?: number; variance?: number; adjusted?: number; movement_count?: number; revenue?: number; cost?: number; profit?: number; average_sale_price?: number; average_purchase_price?: number; net_change?: number };
type Totals = { collected: number; cost: number; profit: number };
type MovementTotals = { delivered: number; sold: number; variance: number };
const today = () => new Date().toISOString().slice(0, 10);
const money = (value: number) => `${Number(value || 0).toLocaleString('ar-EG', { maximumFractionDigits: 2 })} ج.م`;
const litres = (value: number) => `${Number(value || 0).toLocaleString('ar-EG', { maximumFractionDigits: 2 })} لتر`;

export default function DailyReport() {
  const { user } = useRequireAuth(); const stationId = useCurrentStationId(user?.id ?? null);
  const [rows, setRows] = useState<Row[]>([]); const [from, setFrom] = useState(today); const [to, setTo] = useState(today); const [totals, setTotals] = useState<Totals>({ collected: 0, cost: 0, profit: 0 }); const [state, setState] = useState<'loading'|'ready'|'error'>('loading'); const [message, setMessage] = useState('');
  const load = useCallback(async () => { if (!stationId) return; if (from > to) { setMessage('تاريخ البداية يجب أن يسبق تاريخ النهاية.'); return; } setMessage(''); setState('loading'); try { const response = await fetch(`/api/reports/daily?stationId=${encodeURIComponent(stationId)}&from=${from}&to=${to}`); const data = await response.json(); if (!response.ok) throw new Error(data.error); setRows(data.rows || []); setTotals(data.totals || { collected: 0, cost: 0, profit: 0 }); setState('ready'); } catch { setState('error'); } }, [stationId, from, to]);
  useEffect(() => { if (stationId) load(); }, [stationId, load]);
  const movementTotals = useMemo<MovementTotals>(() => rows.reduce<MovementTotals>((all, row) => ({ delivered: all.delivered + Number(row.delivered || 0), sold: all.sold + Number(row.sold || 0), variance: all.variance + Number(row.variance || 0) }), { delivered: 0, sold: 0, variance: 0 }), [rows]);
  return <PageLayout title="التقارير"><div className="report-page">
    <div className="page-heading print-title"><div><h2>تقرير حركة الوقود</h2><p>تحليل شامل للمبيعات والتوريدات والأرباح خلال فترة محددة.</p></div><button className="ui-button secondary no-print" onClick={() => window.print()}>طباعة التقرير</button></div>
    <section className="ui-card report-filter no-print"><div className="form-field"><label>من تاريخ</label><input type="date" value={from} onChange={(e) => setFrom(e.target.value)} /></div><div className="form-field"><label>إلى تاريخ</label><input type="date" value={to} onChange={(e) => setTo(e.target.value)} /></div><button className="ui-button" onClick={load}>عرض التقرير</button>{message && <small className="text-red-600">{message}</small>}</section>
    <p className="report-period">الفترة: {from} — {to}</p>
    <section className="report-kpis"><article><small>إجمالي التوريدات</small><b>{litres(movementTotals.delivered)}</b><span>حركة داخلة للمخزون</span></article><article><small>إجمالي المبيعات</small><b>{litres(movementTotals.sold)}</b><span>كمية مباعة خلال الفترة</span></article><article><small>إجمالي المقبوضات</small><b>{money(totals.collected)}</b><span>قيمة المبيعات المسجلة</span></article><article><small>تكلفة التوريدات</small><b>{money(totals.cost)}</b><span>قيمة الشراء خلال الفترة</span></article><article className="report-profit"><small>صافي الربح</small><b className={totals.profit < 0 ? 'text-red-600' : ''}>{money(totals.profit)}</b><span>المقبوضات − تكلفة التوريدات</span></article></section>
    <section className="ui-card report-table"><div className="ui-toolbar"><div><b>الأداء المالي وحركة المخزون حسب الوقود</b><small className="block mt-1 text-[var(--text-muted)]">القيم المالية بالجنيه المصري، والأسعار متوسطات الفترة المختارة.</small></div><span className="status-badge">{rows.length} نوع وقود</span></div>{state === 'loading' ? <LoadingState /> : state === 'error' ? <ErrorState onRetry={load} /> : rows.length === 0 ? <EmptyState title="لا توجد حركة خلال هذه الفترة" description="غيّر الفترة أو أضف عمليات بيع وتوريد." /> : <div className="table-scroll"><table className="data-table financial-table"><thead><tr><th>الوقود</th><th>توريد / بيع</th><th>المبيعات</th><th>تكلفة التوريد</th><th>صافي الربح</th><th>متوسط بيع</th><th>متوسط شراء</th><th>الفاقد/الفرق</th></tr></thead><tbody>{rows.map((row) => <tr key={row.fuel_type_id || row.fuel_code}><td><b>{row.fuel_name || '—'}</b><small className="block mt-1 text-[var(--text-muted)]">{row.fuel_code || '—'} · {Number(row.movement_count || 0)} حركة</small></td><td><b>{litres(Number(row.delivered))}</b><small className="block mt-1 text-[var(--text-muted)]">بيع: {litres(Number(row.sold))}</small></td><td>{money(Number(row.revenue))}</td><td>{money(Number(row.cost))}</td><td className={Number(row.profit) < 0 ? 'text-red-600 font-bold' : 'text-emerald-700 font-bold'}>{money(Number(row.profit))}</td><td>{money(Number(row.average_sale_price))}/لتر</td><td>{money(Number(row.average_purchase_price))}/لتر</td><td className={Number(row.variance) < 0 ? 'text-red-600 font-bold' : ''}>{litres(Number(row.variance))}</td></tr>)}</tbody><tfoot><tr><td>الإجمالي</td><td>{litres(movementTotals.delivered)}<small className="block">بيع: {litres(movementTotals.sold)}</small></td><td>{money(totals.collected)}</td><td>{money(totals.cost)}</td><td>{money(totals.profit)}</td><td>—</td><td>—</td><td>{litres(movementTotals.variance)}</td></tr></tfoot></table></div>}</section>
  </div></PageLayout>;
}
