import React, { useEffect, useMemo, useState } from 'react';
import Link from 'next/link';
import PageLayout from '../../src/components/PageLayout';
import { EmptyState, ErrorState, LoadingState } from '../../src/components/DataState';
import { Button, PageHeader, SectionCard, StatCard, StatusBadge } from '../../src/components/ui';
import { useRequireAuth } from '../../src/lib/auth';
import { useCurrentStationId } from '../../src/lib/station';
import supabase from '../../src/lib/supabaseClient';
import { formatMoney as formatMoneyValue, formatPrice, formatQuantity } from '../../src/core/numbers';

type Tank = { tank_id: string; tank_code: string; tank_name: string; fuel_type_id: string; fuel_code: string; fuel_name: string; capacity: number; system_quantity: number; available_quantity: number; fill_pct: number; below_minimum: boolean; min_safe_level: number; status: string; meter_readings_count?: number; last_movement_at?: string | null };
type Fuel = { id: string; code: string; name: string; selling_price: number; purchase_price: number; unit?: string; supplier_id?: string | null };
type Delivery = { id: string; business_date: string; delivered_at?: string; supplier_name?: string; supplier_id?: string; fuel_name?: string; fuel_type_id?: string; tank_code?: string; tank_id?: string; quantity: number; unit_cost?: number; total_cost?: number; paid_amount?: number; reference_no?: string; created_by_name?: string };
type Movement = { id: string; business_date: string; occurred_at?: string; txn_type: string; fuel_name?: string; tank_code?: string; quantity_delta: number; running_balance?: number; source_id?: string; created_by_name?: string };
const today = new Intl.DateTimeFormat('en-CA', { timeZone: 'Africa/Cairo' }).format(new Date());
const money = (value: number) => formatMoneyValue(value);
const price = (value: number, withCurrency = true) => formatPrice(value, withCurrency);
const qty = (value: number) => formatQuantity(value, 3);
const movementLabel: Record<string, string> = { sale: 'بيع', delivery: 'توريد', adjustment: 'تسوية', variance_writeoff: 'خصم فرق', reversal: 'إلغاء' };

export default function FuelPage() {
  const { user } = useRequireAuth();
  const stationId = useCurrentStationId(user?.id ?? null);
  const [tanks, setTanks] = useState<Tank[]>([]); const [fuels, setFuels] = useState<Fuel[]>([]); const [deliveries, setDeliveries] = useState<Delivery[]>([]); const [movements, setMovements] = useState<Movement[]>([]); const [query, setQuery] = useState(''); const [fuelFilter, setFuelFilter] = useState(''); const [supplierFilter, setSupplierFilter] = useState(''); const [state, setState] = useState<'loading' | 'ready' | 'error'>('loading');
  async function load() { if (!stationId) return; setState('loading'); try { const [tankResult, fuelResult, deliveryResult, movementResult] = await Promise.all([supabase.from('v_tank_status').select('*').eq('station_id', stationId).eq('is_active', true).order('tank_code'), supabase.from('fuel_types').select('id,code,name,selling_price,purchase_price,display_unit_code,supplier_id').eq('station_id', stationId).eq('is_active', true).order('sort_order'), supabase.from('v_deliveries').select('*').eq('station_id', stationId).eq('status', 'active').order('business_date', { ascending: false }).order('delivered_at', { ascending: false }).limit(300), supabase.from('v_ledger_feed').select('*').eq('station_id', stationId).order('business_date', { ascending: false }).order('occurred_at', { ascending: false }).limit(300)]); if (tankResult.error || fuelResult.error || deliveryResult.error || movementResult.error) throw tankResult.error || fuelResult.error || deliveryResult.error || movementResult.error; setTanks(tankResult.data || []); setFuels(fuelResult.data || []); setDeliveries(deliveryResult.data || []); setMovements(movementResult.data || []); setState('ready'); } catch { setState('error'); } }
  useEffect(() => { load(); }, [stationId]);
  const filteredDeliveries = useMemo(() => deliveries.filter((row) => (!query || [row.supplier_name, row.fuel_name, row.tank_code, row.reference_no].some((value) => String(value || '').toLowerCase().includes(query.toLowerCase()))) && (!fuelFilter || row.fuel_type_id === fuelFilter) && (!supplierFilter || row.supplier_id === supplierFilter)), [deliveries, query, fuelFilter, supplierFilter]);
  const todayDeliveries = deliveries.filter((row) => row.business_date === today); const totalCapacity = tanks.reduce((sum, row) => sum + Number(row.capacity || 0), 0); const totalStock = tanks.reduce((sum, row) => sum + Number(row.system_quantity || 0), 0); const low = tanks.filter((row) => row.below_minimum); const critical = tanks.filter((row) => Number(row.fill_pct || 0) <= 10); const suppliers = Array.from(new Map(deliveries.filter((row) => row.supplier_id).map((row) => [row.supplier_id, { id: row.supplier_id as string, name: row.supplier_name || 'مورد' }])).values());
  return <PageLayout title="الوقود والخزانات"><main dir="rtl"><PageHeader eyebrow="مركز الوقود" title="الوقود والخزانات" description="المخزون والعدادات والتوريدات والحركات من قاعدة البيانات مباشرة." actions={<><Link className="ui-button secondary" href="/settings/fuels">إدارة أنواع الوقود</Link><Link className="ui-button" href="/deliveries/new">إضافة توريد</Link></>} />{state === 'loading' ? <LoadingState /> : state === 'error' ? <ErrorState onRetry={load} /> : <>
    <div className="stats-grid"><StatCard label="أنواع الوقود" value={fuels.length} hint="الأنواع النشطة" /><StatCard label="الخزانات" value={tanks.length} hint={`${tanks.reduce((sum, tank) => sum + Number(tank.meter_readings_count || 1), 0)} قراءة عداد لكل دورة`} tone="success" /><StatCard label="السعة التخزينية" value={qty(totalCapacity)} tone="brand" /><StatCard label="المخزون الحالي" value={qty(totalStock)} tone="success" /><StatCard label="توريدات اليوم" value={todayDeliveries.length} hint={qty(todayDeliveries.reduce((sum, row) => sum + Number(row.quantity || 0), 0))} tone="brand" /><StatCard label="خزانات منخفضة" value={low.length} hint={`${critical.length} حرجة`} tone={critical.length ? 'danger' : 'warning'} /></div>
    <section className="account-cards fuel-tank-grid">{tanks.length ? tanks.map((tank) => <article className="account-card fuel-tank-card" key={tank.tank_id}><header><div><h3>{tank.tank_code} · {tank.tank_name}</h3><small>{tank.fuel_code} · {tank.fuel_name}</small></div><StatusBadge tone={tank.status !== 'operational' ? 'warning' : tank.below_minimum ? 'danger' : 'success'}>{tank.status !== 'operational' ? 'غير متاح' : tank.below_minimum ? 'منخفض' : Number(tank.fill_pct) <= 10 ? 'حرج' : 'طبيعي'}</StatusBadge></header><div className="fuel-level"><span style={{ width: `${Math.min(Math.max(Number(tank.fill_pct || 0), 0), 100)}%` }} /></div><div className="fuel-tank-values"><b>{qty(tank.system_quantity)}</b><span>{Number(tank.fill_pct || 0).toLocaleString('ar-EG')}% من {qty(tank.capacity)}</span></div><Link className="ui-button secondary" href={`/fuel/tanks/${tank.tank_id}`}>تفاصيل الخزان</Link></article>) : <EmptyState title="لا توجد خزانات مسجلة حتى الآن" description="أضف خزانًا من إعدادات الخزانات." />}</section>
    <SectionCard title="أنواع الوقود" description="أسعار البيع والشراء والمخزون وعدد الخزانات المرتبطة"><div className="table-scroll"><table className="data-table"><thead><tr><th>الوقود</th><th>سعر البيع</th><th>سعر الشراء</th><th>الخزانات</th><th>المخزون</th><th>الحالة</th></tr></thead><tbody>{fuels.map((fuel) => { const related = tanks.filter((tank) => tank.fuel_type_id === fuel.id); const stock = related.reduce((sum, tank) => sum + Number(tank.system_quantity || 0), 0); return <tr key={fuel.id}><td><b>{fuel.name}</b><small className="block">{fuel.code}</small></td><td>{price(fuel.selling_price, false)}</td><td>{price(fuel.purchase_price, false)}</td><td>{related.length}</td><td>{qty(stock)}</td><td><StatusBadge tone={related.some((tank) => tank.below_minimum) ? 'warning' : 'success'}>{related.some((tank) => tank.below_minimum) ? 'يحتاج متابعة' : 'طبيعي'}</StatusBadge></td></tr>; })}</tbody></table></div></SectionCard>
    <SectionCard title="التوريدات" description="بحث وفلاتر للتوريدات الفعلية" actions={<Link className="ui-button secondary" href="/deliveries">السجل الكامل</Link>}><div className="ui-toolbar fuel-filters"><input placeholder="بحث بالمورد أو الوقود أو رقم الفاتورة" value={query} onChange={(event) => setQuery(event.target.value)} /><select value={fuelFilter} onChange={(event) => setFuelFilter(event.target.value)}><option value="">كل أنواع الوقود</option>{fuels.map((fuel) => <option key={fuel.id} value={fuel.id}>{fuel.name}</option>)}</select><select value={supplierFilter} onChange={(event) => setSupplierFilter(event.target.value)}><option value="">كل الموردين</option>{suppliers.map((supplier) => <option key={supplier.id} value={supplier.id}>{supplier.name}</option>)}</select><Button variant="ghost" onClick={() => { setQuery(''); setFuelFilter(''); setSupplierFilter(''); }}>إعادة تعيين</Button></div>{filteredDeliveries.length ? <div className="table-scroll"><table className="data-table"><thead><tr><th>العملية</th><th>التاريخ</th><th>المورد</th><th>الوقود / الخزان</th><th>الكمية</th><th>الإجمالي</th><th>المتبقي</th></tr></thead><tbody>{filteredDeliveries.map((row) => <tr key={row.id}><td>{row.reference_no || row.id.slice(0, 8)}</td><td>{row.business_date}</td><td>{row.supplier_name || '—'}</td><td>{row.fuel_name} · {row.tank_code}</td><td>{qty(row.quantity)}</td><td>{money(Number(row.total_cost || Number(row.quantity) * Number(row.unit_cost || 0)))}</td><td>{money(Math.max(Number(row.total_cost || Number(row.quantity) * Number(row.unit_cost || 0)) - Number(row.paid_amount || 0), 0))}</td></tr>)}</tbody></table></div> : <EmptyState title="لا توجد توريدات مسجلة" description="غيّر الفلاتر أو أضف توريدًا جديدًا." />}</SectionCard>
    <SectionCard title="حركات الوقود" description="سجل المخزون القابل للتتبع زمنيًا"><div className="table-scroll"><table className="data-table"><thead><tr><th>التاريخ والوقت</th><th>الحركة</th><th>الوقود / الخزان</th><th>الكمية</th><th>الرصيد بعد</th><th>المستخدم</th></tr></thead><tbody>{movements.map((row) => <tr key={row.id}><td>{row.business_date}<small className="block">{row.occurred_at ? new Date(row.occurred_at).toLocaleTimeString('ar-EG') : '—'}</small></td><td><StatusBadge tone={row.quantity_delta >= 0 ? 'success' : 'info'}>{movementLabel[row.txn_type] || row.txn_type}</StatusBadge></td><td>{row.fuel_name} · {row.tank_code}</td><td>{qty(row.quantity_delta)}</td><td>{qty(row.running_balance || 0)}</td><td>{row.created_by_name || '—'}</td></tr>)}</tbody></table></div></SectionCard>
  </>}</main></PageLayout>;
}
