import React, { useCallback, useEffect, useMemo, useState } from 'react';
import Link from 'next/link';
import PageLayout from '../../src/components/PageLayout';
import { EmptyState, ErrorState, LoadingState } from '../../src/components/DataState';
import { useRequireAuth } from '../../src/lib/auth';
import { useCurrentStationId } from '../../src/lib/station';

type Tank = { tank_id: string; tank_code?: string; tank_name?: string; fuel_name?: string; system_quantity?: number; available_quantity?: number; capacity?: number; fill_pct?: number; status?: string; below_minimum?: boolean; ullage?: number };
const number = (value: unknown) => Number.isFinite(Number(value)) ? Number(value) : 0;
const format = (value: unknown) => new Intl.NumberFormat('ar-EG', { maximumFractionDigits: 0 }).format(number(value));

export default function TanksPage() {
  const { user } = useRequireAuth(); const stationId = useCurrentStationId(user?.id ?? null);
  const [tanks, setTanks] = useState<Tank[]>([]); const [state, setState] = useState<'loading'|'ready'|'error'>('loading'); const [filter, setFilter] = useState('الكل');
  const load = useCallback(async () => { if (!stationId) return; setState('loading'); try { const response = await fetch(`/api/tanks?stationId=${encodeURIComponent(stationId)}`); const data = await response.json(); if (!response.ok) throw new Error(data.error); setTanks(data.tanks || []); setState('ready'); } catch { setState('error'); } }, [stationId]);
  useEffect(() => { if (stationId) load(); }, [stationId, load]);
  const summary = useMemo(() => tanks.reduce((total, tank) => ({ stock: total.stock + number(tank.system_quantity), available: total.available + number(tank.available_quantity), capacity: total.capacity + number(tank.capacity), low: total.low + (tank.below_minimum ? 1 : 0) }), { stock: 0, available: 0, capacity: 0, low: 0 }), [tanks]);
  const fuels = useMemo(() => Object.values(tanks.reduce<Record<string, { name: string; stock: number; capacity: number; tanks: number }>>((result, tank) => { const name = tank.fuel_name || 'غير محدد'; const item = result[name] || { name, stock: 0, capacity: 0, tanks: 0 }; item.stock += number(tank.system_quantity); item.capacity += number(tank.capacity); item.tanks += 1; result[name] = item; return result; }, {})), [tanks]);
  const visibleTanks = filter === 'الكل' ? tanks : tanks.filter((tank) => (tank.fuel_name || 'غير محدد') === filter);
  const fill = summary.capacity ? Math.round((summary.stock / summary.capacity) * 100) : 0;
  return <PageLayout title="الخزانات والمخزون"><main className="inventory-page">
    <header className="inventory-hero"><div><span className="inventory-eyebrow">مراقبة المخزون</span><h2>الخزانات والمخزون</h2><p>تابع الرصيد الفعلي والسعة المتاحة لكل نوع وقود في مكان واحد.</p></div><div className="inventory-actions"><button className="ui-button secondary" onClick={load}>تحديث البيانات</button><Link href="/settings/tanks" className="ui-button">إدارة الخزانات</Link></div></header>
    <section className="inventory-overview"><article className="inventory-main-stat"><div><small>إجمالي الرصيد الحالي</small><strong>{format(summary.stock)} <em>لتر</em></strong><p>{fill}% من إجمالي السعة</p></div><div className="inventory-gauge" style={{ '--fill': `${fill}%` } as React.CSSProperties}><span>{fill}%</span></div></article><article><small>المخزون المتاح للبيع</small><strong>{format(summary.available)} <em>لتر</em></strong><p>بعد استبعاد المخزون الميت</p></article><article><small>السعة الكلية</small><strong>{format(summary.capacity)} <em>لتر</em></strong><p>{tanks.length} خزان مسجل</p></article><article className={summary.low ? 'inventory-alert' : ''}><small>تنبيهات المستوى</small><strong>{summary.low}</strong><p>{summary.low ? 'خزان يحتاج متابعة' : 'جميع المستويات آمنة'}</p></article></section>
    {state === 'loading' ? <LoadingState /> : state === 'error' ? <ErrorState onRetry={load} /> : tanks.length === 0 ? <EmptyState title="لا توجد خزانات مسجلة" description="أضف خزاناً من إعدادات الخزانات ليظهر هنا تلقائياً." /> : <>
      <section className="inventory-fuels"><div className="inventory-section-title"><div><h3>ملخص حسب نوع الوقود</h3><p>إجمالي الرصيد والسعة لكل نوع.</p></div></div><div className="fuel-summary-grid">{fuels.map((fuel, index) => { const percentage = fuel.capacity ? Math.min(100, Math.round(fuel.stock / fuel.capacity * 100)) : 0; return <button key={fuel.name} className={`fuel-summary ${filter === fuel.name ? 'selected' : ''}`} onClick={() => setFilter(filter === fuel.name ? 'الكل' : fuel.name)}><i className={`fuel-accent fuel-accent-${index % 4}`} /><span><b>{fuel.name}</b><small>{fuel.tanks} خزان</small></span><strong>{format(fuel.stock)} <em>لتر</em></strong><div className="fuel-mini-bar"><i style={{ width: `${percentage}%` }} /></div><small>{percentage}% من السعة</small></button>; })}</div></section>
      <section className="inventory-tanks"><div className="inventory-section-title"><div><h3>{filter === 'الكل' ? 'حالة جميع الخزانات' : `خزانات ${filter}`}</h3><p>{visibleTanks.length} خزان ظاهر</p></div>{filter !== 'الكل' && <button className="ui-button secondary" onClick={() => setFilter('الكل')}>عرض الكل</button>}</div><div className="tank-monitor-grid">{visibleTanks.map((tank) => { const percentage = Math.max(0, Math.min(100, number(tank.fill_pct))); const tone = tank.below_minimum ? 'critical' : percentage <= 30 ? 'warning' : 'healthy'; return <article className={`tank-monitor ${tone}`} key={tank.tank_id}><header><div><span className="tank-code">{tank.tank_code || 'خزان'}</span><h4>{tank.tank_name || tank.fuel_name || 'خزان وقود'}</h4></div><span className="tank-status">{tank.below_minimum ? 'منخفض' : percentage <= 30 ? 'تنبيه' : 'طبيعي'}</span></header><div className="tank-quantity"><strong>{format(tank.system_quantity)}</strong><span>لتر</span></div><div className="tank-level"><div><i style={{ width: `${percentage}%` }} /></div><span>{Math.round(percentage)}%</span></div><footer><span>المتاح <b>{format(tank.available_quantity)} لتر</b></span><span>السعة <b>{format(tank.capacity)} لتر</b></span></footer></article>; })}</div></section>
    </>}
  </main></PageLayout>;
}
