import React, { useCallback, useEffect, useMemo, useState } from 'react';
import Link from 'next/link';
import Header from '../src/components/Header';
import { useRequireAuth } from '../src/lib/auth';
import { ErrorState, LoadingState } from '../src/components/DataState';

const STATION_ID = process.env.NEXT_PUBLIC_DEMO_STATION_ID || '11111111-1111-4111-8111-111111111111';
type Snapshot = { stock?: { total_system?: number }; today?: { sold?: number; delivery_count?: number }; reconciliation?: { total_variance?: number; open?: number }; attention?: { critical_alerts?: number } };
type Tank = { tank_id: string; tank_code?: string; fuel_name?: string; fuel_type?: string; system_quantity?: number; current_qty?: number; current_stock?: number; capacity?: number; capacity_liters?: number; fill_pct?: number; percentage?: number };
type IconName = 'stock' | 'sales' | 'operations' | 'report' | 'plus' | 'adjust' | 'transfer';
const number = (value: unknown) => Number.isFinite(Number(value)) ? Number(value) : 0;
const format = (value: unknown) => new Intl.NumberFormat('ar-EG', { maximumFractionDigits: 0 }).format(number(value));

function Icon({ name }: { name: IconName }) {
  const paths: Record<IconName, React.ReactNode> = { stock: <><path d="M6 3h12v18H6z"/><path d="M9 7h6m-6 4h6m-6 4h4"/></>, sales: <><path d="M5 20V6h14v14H5Z"/><path d="m8 15 3-3 2 2 3-4"/></>, operations: <><rect x="5" y="3" width="14" height="18" rx="2"/><path d="M9 8h6m-6 4h6m-6 4h4"/></>, report: <><path d="M4 20V4m0 16h17"/><path d="M8 16v-4m4 4V8m4 8v-6"/></>, plus: <path d="M12 5v14M5 12h14"/>, adjust: <><path d="M5 7h14M5 17h14"/><circle cx="9" cy="7" r="2"/><circle cx="15" cy="17" r="2"/></>, transfer: <path d="M6 7h11m-3-3 3 3-3 3M18 17H7m3 3-3-3 3-3"/> };
  return <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round">{paths[name]}</svg>;
}
function Graph() { return <div className="dash-chart"><svg viewBox="0 0 650 230" preserveAspectRatio="none"><defs><linearGradient id="fill" x1="0" x2="0" y1="0" y2="1"><stop stopColor="#1769f5" stopOpacity=".2"/><stop offset="1" stopColor="#1769f5" stopOpacity="0"/></linearGradient></defs>{[35,85,135,185].map(y => <path key={y} d={`M0 ${y}H650`} stroke="#e7edf5"/>)}<path d="M0 165 90 136 180 103 270 130 360 125 450 51 540 142 650 68 650 205H0Z" fill="url(#fill)"/><path d="M0 165 90 136 180 103 270 130 360 125 450 51 540 142 650 68" fill="none" stroke="#1769f5" strokeWidth="3"/></svg><div>{['17 مايو','19 مايو','20 مايو','21 مايو','22 مايو','23 مايو'].map(d => <span key={d}>{d}</span>)}</div></div>; }

export default function Dashboard() {
  const { user, isLoading } = useRequireAuth(); const [snapshot, setSnapshot] = useState<Snapshot | null>(null); const [tanks, setTanks] = useState<Tank[]>([]); const [state, setState] = useState<'loading'|'ready'|'error'>('loading');
  const load = useCallback(async () => { setState('loading'); try { const [overview, inventory] = await Promise.all([fetch(`/api/station/snapshot?stationId=${STATION_ID}`), fetch(`/api/tanks?stationId=${STATION_ID}`)]); if (!overview.ok || !inventory.ok) throw Error(); const [a, b] = await Promise.all([overview.json(), inventory.json()]); setSnapshot(a.snapshot || null); setTanks(b.tanks || []); setState('ready'); } catch { setState('error'); } }, []);
  useEffect(() => { if (user) load(); }, [user, load]);
  const fuels = useMemo(() => tanks.slice(0, 3).map((tank) => { const quantity = number(tank.system_quantity ?? tank.current_qty ?? tank.current_stock); const capacity = number(tank.capacity ?? tank.capacity_liters); return { name: tank.fuel_name || tank.fuel_type || tank.tank_code || 'خزان وقود', quantity, percent: tank.fill_pct ?? tank.percentage ?? (capacity ? quantity / capacity * 100 : 0) }; }), [tanks]);
  const cards: { title: string; value: unknown; unit: string; icon: IconName; hint: string }[] = [{ title: 'المخزون الإجمالي', value: snapshot?.stock?.total_system, unit: 'لتر', icon: 'stock', hint: 'الرصد الحالي' }, { title: 'كمية الوقود المباعة', value: snapshot?.today?.sold, unit: 'لتر', icon: 'sales', hint: 'مبيعات اليوم' }, { title: 'عدد العمليات', value: snapshot?.today?.delivery_count, unit: 'عملية', icon: 'operations', hint: 'توريدات اليوم' }, { title: 'إجمالي التسويات', value: snapshot?.reconciliation?.total_variance, unit: 'لتر', icon: 'adjust', hint: `${snapshot?.reconciliation?.open || 0} بانتظار المراجعة` }];
  const actions: { href: string; icon: IconName; label: string }[] = [{ href: '/reconciliation', icon: 'adjust', label: 'تسوية وردية' }, { href: '/tanks', icon: 'transfer', label: 'تحويل مخزون' }, { href: '/deliveries/new', icon: 'plus', label: 'إضافة فاتورة شراء' }, { href: '/sales/new', icon: 'sales', label: 'إضافة بيع' }, { href: '/reports/daily', icon: 'report', label: 'عرض التقارير' }];
  if (isLoading || state === 'loading') return <div className="app-main"><Header /><main className="dashboard-page"><LoadingState /></main></div>;
  if (!user) return null;
  return <div className="app-main"><Header /><main className="dashboard-page">{state === 'error' ? <ErrorState onRetry={load} /> : <><section className="dash-title"><div><h1>الرئيسية</h1><p>نظرة عامة على أداء المحطة</p></div><button onClick={load}>اليوم: {new Intl.DateTimeFormat('ar-EG', { day: 'numeric', month: 'long' }).format(new Date())}</button></section><section className="dash-kpis">{cards.map(card => <article key={card.title}><span><Icon name={card.icon} /></span><p>{card.title}</p><strong>{format(card.value)}</strong><small>{card.unit}</small><footer><i />{card.hint}</footer></article>)}</section><section className="dash-analytics"><article className="dash-panel"><header><h2>المبيعات خلال آخر 7 أيام</h2><small>يظهر الرسم عند توفر سجل المبيعات</small></header><Graph /></article><article className="dash-panel"><header><h2>المخزون الحالي في الخزانات</h2></header><div className="stock-summary"><div className="stock-ring"><div><small>إجمالي</small><b>{format(snapshot?.stock?.total_system)}</b><small>لتر</small></div></div><div className="stock-list">{fuels.length ? fuels.map((fuel, index) => <div key={fuel.name}><i className={`fuel-${index}`} /><span><b>{fuel.name}</b><small>{format(fuel.quantity)} لتر</small></span><strong>{Math.round(fuel.percent)}%</strong></div>) : <p>لا تتوفر بيانات خزانات.</p>}</div></div></article></section><section className="dash-actions"><h2>إجراءات سريعة</h2><div>{actions.map(action => <Link href={action.href} key={action.label}><span><Icon name={action.icon} /></span><b>{action.label}</b></Link>)}</div></section></>}</main></div>;
}
