import React, { FormEvent, useEffect, useState } from 'react';
import Link from 'next/link';
import { useRouter } from 'next/router';
import supabase from '../src/lib/supabaseClient';
import { useAuth } from '../src/lib/auth';
import ThemeToggle from '../src/components/ThemeToggle';

function Icon({ name }: { name: 'mail'|'lock'|'eye'|'chart'|'tank'|'shield'|'briefcase'|'login' }) {
  const paths = { mail: <><rect x="3" y="5" width="18" height="14" rx="2"/><path d="m3 7 9 6 9-6"/></>, lock: <><rect x="4" y="10" width="16" height="11" rx="2"/><path d="M8 10V7a4 4 0 0 1 8 0v3"/></>, eye: <><path d="M2 12s3.5-7 10-7 10 7 10 7-3.5 7-10 7S2 12 2 12Z"/><circle cx="12" cy="12" r="3"/></>, chart: <><path d="M4 20V4m0 16h17"/><path d="m7 16 4-5 3 2 5-7"/></>, tank: <><path d="M6 7h12v11H6zM9 7V4h6v3M8 18v2m8-2v2M6 12h12"/></>, shield: <><path d="M12 3 20 6v5c0 5-3.2 8.4-8 10-4.8-1.6-8-5-8-10V6l8-3Z"/><path d="m9 12 2 2 4-5"/></>, briefcase: <><rect x="3" y="7" width="18" height="13" rx="2"/><path d="M8 7V4h8v3m-13 5h18"/></>, login: <><path d="m10 17 5-5-5-5m5 5H3"/><path d="M15 3h4a2 2 0 0 1 2 2v14a2 2 0 0 1-2 2h-4"/></> };
  return <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true">{paths[name]}</svg>;
}
function FlameLogo() { return <svg className="signin-flame" viewBox="0 0 48 48" aria-hidden="true"><defs><linearGradient id="flame" x1="10" y1="4" x2="36" y2="44"><stop stopColor="#31d9eb"/><stop offset=".5" stopColor="#1876f8"/><stop offset="1" stopColor="#123fc4"/></linearGradient></defs><path fill="url(#flame)" d="M24 3C19 11 10 18 10 29c0 8 6 14 14 14s14-6 14-14c0-10-7-17-11-26-1 11-8 15-8 23 0 4 2 7 5 9-6-1-10-6-10-12 0-7 6-12 10-20Z"/></svg>; }
function authMessage(error: string) { const value = error.toLowerCase(); if (value.includes('invalid')) return 'البريد الإلكتروني أو كلمة المرور غير صحيحة.'; if (value.includes('too many')) return 'تم تجاوز عدد المحاولات المسموح بها، حاول لاحقاً.'; return 'تعذر تسجيل الدخول. تحقق من اتصالك وحاول مرة أخرى.'; }

export default function SignIn() {
  const { user, isLoading } = useAuth(); const router = useRouter(); const [email, setEmail] = useState(''); const [password, setPassword] = useState(''); const [showPassword, setShowPassword] = useState(false); const [remember, setRemember] = useState(false); const [message, setMessage] = useState<string | null>(null); const [submitting, setSubmitting] = useState(false);
  useEffect(() => { if (!isLoading && user) router.replace('/'); }, [isLoading, router, user]);
  async function submit(event: FormEvent) { event.preventDefault(); if (submitting) return; setSubmitting(true); setMessage(null); try { const { data, error } = await supabase.auth.signInWithPassword({ email: email.trim(), password }); if (error) { setMessage(authMessage(error.message)); return; } if (data.session) { router.replace('/'); return; } setMessage('تم تسجيل الدخول، جارٍ التحقق من الجلسة…'); } catch { setMessage('حدث خطأ غير متوقع. حاول مرة أخرى.'); } finally { setSubmitting(false); } }
  return <main className="signin-page" dir="rtl"><section className="signin-hero"><div className="signin-hero-image" /><div className="signin-hero-content"><div className="signin-brand"><FlameLogo /><span>Al Taawoun<span>.</span></span></div><div className="signin-copy"><h1>{'\u0627\u0644\u062a\u0639\u0627\u0648\u0646'}</h1><p>إدارة دقيقة للمخزون والمبيعات والتسويات<br />والتقارير في منصة واحدة</p></div><div className="signin-features"><Feature icon="chart" title="تقارير دقيقة"/><Feature icon="tank" title="إدارة المبيعات"/><Feature icon="briefcase" title="مراقبة المخزون"/><Feature icon="shield" title="آمن وموثوق"/></div><div className="signin-security"><span><Icon name="shield" /></span><div><b>نظام آمن وسريع</b><small>بياناتك محمية بأعلى معايير الأمان</small></div></div></div></section><section className="signin-panel"><div className="signin-tools"><ThemeToggle /></div><div className="signin-form-wrap"><div className="signin-heading"><h2>مرحباً بك في <em>Al Taawoun</em></h2><p>سجّل الدخول للمتابعة</p></div><form onSubmit={submit} className="signin-form"><label>البريد الإلكتروني<div className="signin-input"><Icon name="mail"/><input required type="email" autoComplete="email" value={email} onChange={(e) => setEmail(e.target.value)} placeholder="أدخل بريدك الإلكتروني" /></div></label><label>كلمة المرور<div className="signin-input"><Icon name="lock"/><input required type={showPassword ? 'text' : 'password'} autoComplete="current-password" value={password} onChange={(e) => setPassword(e.target.value)} placeholder="أدخل كلمة المرور"/><button type="button" onClick={() => setShowPassword((value) => !value)} aria-label="إظهار كلمة المرور"><Icon name="eye"/></button></div></label><div className="signin-options"><Link href="/forgot-password">نسيت كلمة المرور؟</Link><label><input type="checkbox" checked={remember} onChange={(e) => setRemember(e.target.checked)} /> تذكرني</label></div>{message && <p className="signin-message" role="alert">{message}</p>}<button className="signin-submit" disabled={submitting || isLoading}>{submitting ? 'جارٍ تسجيل الدخول…' : <><Icon name="login"/> دخول</>}</button></form></div><p className="signin-footer">جميع الحقوق محفوظة © Al Taawoun 2024</p></section></main>;
}
function Feature({ icon, title }: { icon: 'chart'|'tank'|'briefcase'|'shield'; title: string }) { return <div><span><Icon name={icon} /></span><b>{title}</b></div>; }
