import React, { FormEvent, useCallback, useEffect, useState } from 'react';
import PageLayout from '../src/components/PageLayout';
import supabase from '../src/lib/supabaseClient';
import { useRequireAuth } from '../src/lib/auth';
import { EmptyState, ErrorState, LoadingState } from '../src/components/DataState';

type Profile = { id: string; full_name: string; email: string; role: 'manager' | 'supervisor'; is_active: boolean; last_seen_at?: string | null };
const blank = { full_name: '', email: '', password: '', role: 'supervisor' as Profile['role'], is_active: true };

export default function UsersPage() {
  const { user } = useRequireAuth(); const [rows, setRows] = useState<Profile[]>([]); const [state, setState] = useState<'loading' | 'ready' | 'error'>('loading');
  const [form, setForm] = useState(blank); const [editing, setEditing] = useState<Profile | null>(null); const [message, setMessage] = useState('');
  const token = async () => (await supabase.auth.getSession()).data.session?.access_token || '';
  const load = useCallback(async () => { setState('loading'); try { const response = await fetch('/api/users', { headers: { Authorization: `Bearer ${await token()}` } }); const data = await response.json(); if (!response.ok) throw Error(data.error); setRows((data.users || []).filter((profile: Profile) => profile.is_active)); setState('ready'); } catch { setState('error'); } }, []);
  useEffect(() => { if (user) load(); }, [user, load]);
  async function submit(event: FormEvent) { event.preventDefault(); setMessage(''); const editingNow = editing; const response = await fetch('/api/users', { method: editingNow ? 'PATCH' : 'POST', headers: { 'Content-Type': 'application/json', Authorization: `Bearer ${await token()}` }, body: JSON.stringify(editingNow ? { ...form, id: editingNow.id, email: undefined } : form) }); const data = await response.json(); if (!response.ok) return setMessage(data.error || 'تعذر حفظ المستخدم.'); setForm(blank); setEditing(null); setMessage(editingNow ? 'تم تحديث المستخدم.' : 'تم إنشاء المستخدم.'); load(); }
  async function remove(profile: Profile) { if (!window.confirm(`هل تريد إيقاف حساب ${profile.full_name} ومنعه من الدخول؟`)) return; const response = await fetch('/api/users', { method: 'DELETE', headers: { 'Content-Type': 'application/json', Authorization: `Bearer ${await token()}` }, body: JSON.stringify({ id: profile.id }) }); const data = await response.json(); if (!response.ok) return setMessage(data.error || 'تعذر إيقاف المستخدم.'); setRows((current) => current.filter((row) => row.id !== profile.id)); setMessage('تم إيقاف المستخدم مع الحفاظ على سجلاته.'); }
  function edit(profile: Profile) { setEditing(profile); setForm({ full_name: profile.full_name, email: profile.email, password: '', role: profile.role, is_active: profile.is_active }); window.scrollTo({ top: 0, behavior: 'smooth' }); }
  return <PageLayout title="المستخدمون والصلاحيات"><main className="users-page" dir="rtl">
    <div className="page-heading"><div><span className="eyebrow">إدارة الفريق</span><h2>المستخدمون والصلاحيات</h2><p>أضف أعضاء الفريق وحدد صلاحيات كل حساب بأمان.</p></div><span className="status-badge">{rows.length} مستخدم نشط</span></div>
    <div className="users-layout"><form onSubmit={submit} className="ui-card form-card form-grid users-form"><h3>{editing ? 'تعديل المستخدم' : 'إضافة مستخدم'}</h3><div className="form-field"><label>الاسم الكامل</label><input required value={form.full_name} onChange={(e) => setForm({ ...form, full_name: e.target.value })} /></div><div className="form-field"><label>البريد الإلكتروني</label><input required disabled={!!editing} type="email" value={form.email} onChange={(e) => setForm({ ...form, email: e.target.value })} /></div><div className="form-field"><label>{editing ? 'كلمة مرور جديدة (اختياري)' : 'كلمة المرور'}</label><input required={!editing} minLength={6} type="password" value={form.password} onChange={(e) => setForm({ ...form, password: e.target.value })} /></div><div className="form-field"><label>الدور</label><select value={form.role} onChange={(e) => setForm({ ...form, role: e.target.value as Profile['role'] })}><option value="supervisor">مشرف</option><option value="manager">مدير</option></select></div><label className="users-toggle"><input type="checkbox" checked={form.is_active} onChange={(e) => setForm({ ...form, is_active: e.target.checked })} /> حساب نشط</label>{message && <p className="users-message">{message}</p>}<div className="users-actions"><button className="ui-button">{editing ? 'حفظ التعديل' : 'إضافة المستخدم'}</button>{editing && <button type="button" className="ui-button secondary" onClick={() => { setEditing(null); setForm(blank); }}>إلغاء</button>}</div></form>
      <section className="ui-card users-list"><div className="ui-toolbar"><div><b>قائمة الفريق</b><small>المدير فقط يستطيع إدارة الحسابات.</small></div></div>{state === 'loading' ? <LoadingState /> : state === 'error' ? <ErrorState onRetry={load} /> : rows.length === 0 ? <EmptyState title="لا يوجد مستخدمون" description="أضف أول مستخدم للفريق من النموذج." /> : <div className="table-scroll"><table className="data-table"><thead><tr><th>المستخدم</th><th>الدور</th><th>الحالة</th><th>آخر نشاط</th><th>الإجراءات</th></tr></thead><tbody>{rows.map((profile) => <tr key={profile.id}><td><b>{profile.full_name}</b><small>{profile.email}</small></td><td><span className="status-badge">{profile.role === 'manager' ? 'مدير' : 'مشرف'}</span></td><td>نشط</td><td>{profile.last_seen_at ? new Intl.DateTimeFormat('ar-EG', { dateStyle: 'medium' }).format(new Date(profile.last_seen_at)) : '—'}</td><td><div className="users-row-actions"><button className="ui-button secondary" onClick={() => edit(profile)}>تعديل</button><button className="ui-button danger" disabled={profile.id === user?.id || profile.email.toLowerCase() === 'markode@gmail.com'} onClick={() => remove(profile)}>إيقاف</button></div></td></tr>)}</tbody></table></div>}</section>
    </div>
  </main></PageLayout>;
}
